### ISSUE TITLE
Adding global variable to Cypress by parameter (--env var=value) is not working.

### ISSUE THREAD

**Issue by pr-it** [briebug/cypress-schematic#105]
**Describe the bug**
In case when I am starting angular app and cypress flag --env to inject global parameter is not working.

**To Reproduce**
Run the Angular app with Cypress instance:
ng run aplicationName:cypress-open --env var=value
value is not available in Cypress tests.
I have tested also with
ng run aplicationName:cypress-open --env var=value --spec path/test.ts
ng run aplicationName:cypress-open --spec path/test.ts --env var=value
ng run aplicationName:cypress-run --env var=value --spec path/test.ts 
ng run aplicationName:cypress-run --spec path/test.ts --env var=value
and flag --spec is working properly. Flag -env is not working. 

Also, I have tested it on a clear Cypress package without Angular, and flag --env is working fine.

**Expected behavior**
Flag --env should provide the possibility to inject global variable

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10, Ubuntu
 - Browser [e.g. Electron, Chrome]
 - Version [e.g. last version of browser]

**Additional context**
In case of any questions don't hesitate to contact me directly: pawel.funfell@gmail.com

**Comment by pr-it** [comment]
Kind remainder. Any update ?

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
