### ISSUE TITLE
Project status now that @cypress/schematic is out

### ISSUE THREAD

**Issue by cexbrayat** [briebug/cypress-schematic#106]
Now that the code [has been duplicated into Cypress codebase](https://github.com/cypress-io/cypress/pull/16449) and released as `@cypress/schematic`, what is the status of the current project @anthonymjones ?

Should we consider it deprecated and migrate to `@cypress/schematic`?
The CLI team [added a reference into the official docs](https://github.com/angular/angular-cli/pull/20748).

cc @admah

**Comment by anthonymjones** [comment]
Hey Cédric! 

I think what is very likely to happen is we will deprecate @briebug/cypress-schematic and point to the official @cypress/schematic from the README. 

I am actually in the process of working out the details with Gleb and Amir from the Cypress team. I'll let you know when I have more info.

**Comment by anthonymjones** [comment]
@cexbrayat & @muuvmuuv - thank you both for all your help over the past couple of years. As you may already know, I've decided to deprecate the schematic and direct users to the official @cypress/schematic.  In case you haven't seen it already, @admah did update their README with a Community Recognition section at the bottom, and I've added a "Thank You" to all the contributors here. 

I know they would love to have you continue to contribute to the official version, and their road map for the schematic is definitely exciting. 

Feel free to reach out if you have any questions or thoughts! anthony.jones@briebug.com

**Comment by cexbrayat** [comment]
Thanks @anthonymjones 

We moved our projects to the official schematic and I started to contribute there as well.
Thanks for the time you've put in this project!
