### ISSUE TITLE
Add support for Angular 12: Use "$id" for schema ID.

### ISSUE THREAD

**Issue by mraible** [briebug/cypress-schematic#111]
**Describe the bug**

If I use `ng add @briebug/cypress-schematic` to add Cypress to an Angular 12 project, I see the following warning:

```
"BuilderProgressSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
```

Also, I'm prompted to remove Protractor when it doesn't exist.

**To Reproduce**

```
npm install -g @angular/cli@12
ng new ng-demo
cd ng-demo
ng add @briebug/cypress-schematic
```

**Expected behavior**

I don't expect to see a warning about the schema, nor a prompt to remove Protractor.

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
