### ISSUE TITLE
Support the --ci-build-id Flag

### ISSUE THREAD

**Issue by cshouts-tasc** [briebug/cypress-schematic#112]
### Description
When running tests in parallel we can optionally pass a build id to uniquely identify a CI build.

It would be beneficial to parallel CI users to add support for setting the CI build id in the e2e builder options.

### Cypress docs for the --ci-build-id flag
https://docs.cypress.io/guides/guides/command-line#cypress-run-ci-build-id-lt-id-gt

**Comment by muuvmuuv** [comment]
Cypress added their own schematics based on this project: https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic

See: https://github.com/briebug/cypress-schematic/issues/106

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
