### ISSUE TITLE
Cypress 8 support

### ISSUE THREAD

**Issue by ahnpnl** [briebug/cypress-schematic#113]
**Is your feature request related to a problem? Please describe.**
**N.A.**

**Describe the solution you'd like**
When upgrade Cypress to 8.0.0, `ng update` prevents from doing that because incompatible supported version from this project.

**Describe alternatives you've considered**
`ng update` should be successful.

**Additional context**
**N.A.**

**Comment by fogshot** [comment]
Even worse, when executing the schematic on a virgin project, the schematic installs cypress @latest (currently 8.0), but has a conflicting peer dependency of "^7.0.0". As a workaround, you have to manually downgrade the dependency in your package.json, then re-run the schematic.

NPM output:
`
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: cypress@8.0.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"8.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^7.0.0" from @briebug/cypress-schematic@5.0.0
npm ERR! node_modules/@briebug/cypress-schematic
npm ERR!   dev @briebug/cypress-schematic@"^5.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
`

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
