### ISSUE TITLE
had to run ng add command twice

### ISSUE THREAD

**Issue by robert-king** [briebug/cypress-schematic#15]
Roberts-MacBook-Pro-3:front-end robertking$ ng add @briebug/cypress-schematic
Installing packages for tooling via npm.

> fsevents@1.2.9 install /Users/robertking/go/src/bitbucket.org/borndigital-nz/barker.mybarker/front-end/node_modules/@briebug/cypress-schematic/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/robertking/go/src/bitbucket.org/borndigital-nz/barker.mybarker/front-end/node_modules/@briebug/cypress-schematic/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote
npm WARN @angular/core@8.2.14 requires a peer of zone.js@~0.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN @fullcalendar/angular@4.3.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fullcalendar/angular@4.3.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.2.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

+ @briebug/cypress-schematic@2.0.0
added 87 packages from 55 contributors and audited 25359 packages in 21.487s
found 7 vulnerabilities (1 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
An unhandled exception occurred: Cannot find module '/Users/robertking/go/src/bitbucket.org/borndigital-nz/barker.mybarker/front-end/node_modules/@briebug/cypress-schematic/package.json'
See "/private/var/folders/rg/4bkqmv6j6mv_v07mmls232v00000gn/T/ng-BRin8O/angular-errors.log" for further details.
Roberts-MacBook-Pro-3:front-end robertking$

second time running:

Roberts-MacBook-Pro-3:front-end robertking$ ng add @briebug/cypress-schematic
Skipping installation: Package already installed
? Would you like to remove Protractor from the project? Yes
DELETE e2e
CREATE cypress/tsconfig.json (114 bytes)
CREATE cypress/plugins/cy-ts-preprocessor.js (387 bytes)
CREATE cypress/plugins/index.js (155 bytes)
UPDATE package.json (2889 bytes)
UPDATE angular.json (3716 bytes)

> cypress@3.6.1 postinstall /Users/robertking/go/src/bitbucket.org/borndigital-nz/barker.mybarker/front-end/node_modules/cypress
> node index.js --exec install

 ✔  Downloaded Cypress
 ✔  Unzipped Cypress
 ✔  Finished Installation /Users/robertking/Library/Caches/Cypress/3.6.1
npm WARN @angular/core@8.2.14 requires a peer of zone.js@~0.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN @fullcalendar/angular@4.3.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fullcalendar/angular@4.3.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.2.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 99 packages from 74 contributors, removed 32 packages, moved 5 packages and audited 26844 packages in 68.287s
found 5 vulnerabilities (1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Roberts-MacBook-Pro-3:front-end robertking$ 

perhaps this is because i ran an ng update --all beforehand

**Comment by anthonymjones** [comment]
Hi @robert-king, I just released v3.0.0. Would you mind trying again and seeing if this is still an issue?

Thanks!

**Comment by anthonymjones** [comment]
Closing this issue... Please let me know if this is still an issue after upgrading and should be re-opened. Thanks!
