### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module' 

### ISSUE THREAD

**Issue by StephenFluin** [briebug/cypress-schematic#22]
Setup;
```
npx @angular/cli@next new my-app
cd my-app
ng add @briebug/cypress-schematics
ng e2e
Click on "run all tests"
```

**Expected outcome**
Tests run and either pass or fail

**Observed outcome**
`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (17:0) while parsing /usr/local/google/home/stephenfluin/workspace/test/cypress-testing/cypress/support/index.ts while parsing file: /usr/local/google/home/stephenfluin/workspace/test/cypress-testing/cypress/support/index.ts`

**Versions**
Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2

**Comment by anthonymjones** [comment]
Thank you, @StephenFluin. Looking into it now

**Comment by anthonymjones** [comment]
@StephenFluin, I just tested out the schematic/builder in Angular 8.2.13 & 9.0.0-rc.7, and it appears to work. 

I had to take a few steps to test it out in a project where I already used the schematic. 
- npm uninstall @briebug/cypress-schematic
- delete the cypress directory & cypress.json 
- enter "n" for the "Would you like to remove Protractor from the project?" prompt
(a future release will handle the last two steps more gracefully)

Thanks for catching this issue!
