### ISSUE TITLE
Support workspaces with multiple projects

### ISSUE THREAD

**Issue by mhamern** [briebug/cypress-schematic#30]
**Is your feature request related to a problem? Please describe.**
I would love to use the schematic in workspaces with multiple projects. 

When developing libraries, I usually create workspace with two projects - one for the library and one for app (for testing, usage example purposes).

You can generate the same workspace by running following commands.

```
ng new my-workspace --create-application=false
cd my-workspace
ng generate application my-example-app
ng generate library my-library
```
Running the schematic in workspace directory (where angular.json is located) and confirming delete protractor promt results in `path "/e2e" does not exist.`.

**Describe the solution you'd like**
I would add add optional parameter to specify name of the project (as some angular cli schematics does). If not provided, default project from angular.json would be used. 

Expected result is to have a possibility to use the schematic like `ng add @briebug/cypress-schematic --project=my-example-app`

**Describe alternatives you've considered**

Running the schematic in `./projects/my-example-app` does not help.

**Comment by anthonymjones** [comment]
@mhamern - Thank you for the feature request! I'll look into implementing this.
