### ISSUE TITLE
Support cypress 5x

### ISSUE THREAD

**Issue by muuvmuuv** [briebug/cypress-schematic#42]
**Is your feature request related to a problem? Please describe.**

Installing this schematics displays this npm warning:

```
npm WARN @briebug/cypress-schematic@3.3.0 requires a peer of cypress@^3.6.1 but none is installed. You must install peer dependencies yourself.
```

**Comment by alex88** [comment]
@muuvmuuv in the meantime
```
"resolutions": {
  "@briebug/cypress-schematic/cypress": "^4.9.0"
}
```
works for using cypress 4 and there are no isues

**Comment by muuvmuuv** [comment]
Updated to v5.

One bug I noticed is that the browser is not passed properly: 

- https://github.com/briebug/cypress-schematic/blob/master/src/builders/cypress/index.ts#L95
- https://docs.cypress.io/guides/guides/module-api.html#Options-1

So using `browser` does nothing atm. As well as headless ^^.
