### ISSUE TITLE
when i try to add schematic as dependency it throughs an error

### ISSUE THREAD

**Issue by wasiqkhan786** [briebug/cypress-schematic#44]
when i try to add schematic as dependency npm install -g @briebug/cypress-schematic it throughs an error 
 **npm WARN @briebug/cypress-schematic@3.3.0 requires a peer of cypress@^3.6.1 but none is installed. You must install peer dependencies yourself.**
and 2nd when i run this command ng add @briebug/cypress-schematic it also through an error
**The add command requires to be run in an Angular project, but a project definition could not be found.**

**Comment by muuvmuuv** [comment]
Might be fixed after #58 is released. Just check for the next releases.

Anyway you should not install those globally. Try this:

1. `cd` into your project root where the `package.json` and `angular.json` is located
2. `ng add @briebug/cypress-schematic`

And if this does not work, can you please post the output of `ng version` here and your `angular.json`?

I have tested it with a newly generated NG project without errors so I guess you are just running an older NG version or forgot to `cd` into your project.

As a test you could just run this to see if it produces no errors in a newly generated project:

1. `ng new test --minimal --no-interactive`
2. `cd test`
3. `ng add @briebug/cypress-schematic --addCypressTestScripts`
4. `? Would you like to remove Protractor from the project? No`
5. => ✔ Packages installed successfully.

**Comment by anthonymjones** [comment]
v4.0.0 is now released, which may clear up the version issue (thanks, @muuvmuuv!). 

@wasiqkhan786 - Are you working with a singular application or an Angular Workspace?
