### ISSUE TITLE
Options take no effect?

### ISSUE THREAD

**Issue by muuvmuuv** [briebug/cypress-schematic#47]
**Describe the bug**
 I am setting up a CI target for e2e tests and wanted to disable screenshots, videos and run all in parallel. Unfortunately settings those options does nothing.

```json
        "e2e-ci": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "aqua:serve",
            "headless": true,
            "browser": "chrome",
            "parallel": true,
            "record": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "aqua:serve:production"
            }
          }
        }
```

**To Reproduce**
1. Enable parallel and disable video
2. Run

**Expected behavior**

No video, no screenshots and run in parallel.

**Screenshots**

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.5.0                                                                              │
  │ Browser:    Electron 80 (headless)                                                             │
  │ Specs:      3 found (aqua/filter/aside.ts, aqua/header.ts, spec.ts)                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  aqua/filter/aside.ts                                                            (1 of 3)


  ✓ sequenz filter should be expanded (2284ms)
  ✓ should expand sequenz filter (186ms)
  ✓ should collapse sequenz filter (145ms)
  ✓ should nav tabs to saved (145ms)

  4 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     aqua/filter/aside.ts                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/marvinheilemann/Development/Additive/Kunden/Fraunhof     (1 second)
                          er/AQUA-Filter/cypress/videos/aqua/filter/aside.ts.mp4


```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Version 3.3.0

**Additional context**

I would also like to know why it is saying "Browser: Electron 80 (headless)" when I declared "chrome".

**Comment by muuvmuuv** [comment]
Okay, parallel and record are not what I initially thought. Record just publishs to the dashboard and parallel only works with record, so forget about those.

Tested with `./node_modules/.bin/cypress run --browser chrome --headless` which runs chrome correctly.

**Comment by LukasKlement** [comment]
It appears that this is indeed a bug. In angular.json, the following two:

`"e2e": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "myapp:serve",
            "watch": true,
            "browser": "chrome",
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "myapp:serve:production"
            }
          }
        },
        "e2e-ci": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "myapp:serve",
            "browser": "chrome",
            "headless": true
          },
          "configurations": {
            "production": {
              "devServerTarget": "myapp:serve:production"
            }
          }
        },`

- e2e works correctly and executes cypress with the Chrome browser
- e2e-ci runs Electron 80 (headless) instead of Chrome

**Comment by Renaud009** [comment]
"spec" options not passed to cypress as well

**Comment by muuvmuuv** [comment]
I have opened a PR which probably fixes this @Renaud009

**Comment by Renaud009** [comment]
Indeed I have tested with cypress-v5 branch and options are passed to cypress runner with success (only tested "browser" and "spec" tho)

Any idea when the new release will be made?

Thank you and keep up the good work!

**Comment by Renaud009** [comment]
Is it possible that headless option is now overwritten to true? my `ng e2e` always run headless since i took cypress-v5 branch
Here's my angular.json
```json
"e2e": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "app:serve",
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "app:serve:production"
            }
          }
        },
```

**Comment by Renaud009** [comment]
Ohh i need to to set watch: true as a workaround..

**Comment by muuvmuuv** [comment]
I have not touched that part nor tested that specific case but could be since `!watch` always returns false or true so `headless` is ignored: https://github.com/briebug/cypress-schematic/blob/master/src/builders/cypress/index.ts#L82
