### ISSUE TITLE
Add: Chainable interfae to command.ts to support custom commands

### ISSUE THREAD

**Issue by digitaldrummerj** [briebug/cypress-schematic#5]
In order to write custom commands in TypeScript, you have to add the following code to the command.ts file and then define each command inside of the chainable interface.

```TypeScript
declare global {
  namespace Cypress {
     interface Chainable {
     }
   }
 }
```

**Comment by anthonymjones** [comment]
Closing this issue... I just released v3.0.0. Please let me know if this is still an issue and should be re-opened. Thanks!
