### ISSUE TITLE
spec paramter in angular.json

### ISSUE THREAD

**Issue by ThRintelen** [briebug/cypress-schematic#50]
**Is your feature request related to a problem? Please describe.**
I want to call the tests only for one project. 
`ng e2e project1`

**Describe the solution you'd like**
cypress has the spec parameter to say wich tests should run.

`"e2e": {
                    "builder": "@briebug/cypress-schematic:cypress",
                    "options": {
                        "devServerTarget": "project1:serve",
                        "watch": true,
                        "headless": true,
                        "spec": "cypress/integration/project1/**/*"
                    },
                    "configurations": {
                        "production": {
                            "devServerTarget": "project1:serve:production"
                        }
                    }
                }`

Is there an other solution for this problem?

**Comment by BabayevEldar** [comment]
Did you manage to run tests for a specific project?
In my case, every time a new cypress folder is created

**Comment by anthonymjones** [comment]
The functionality for Angular Workspaces has not yet been implemented, but it is hopefully coming soon.

**Comment by ThRintelen** [comment]
With the latest version it seems to work. This is my angular.json part:
`"e2e": {
                    "builder": "@briebug/cypress-schematic:cypress",
                    "options": {
                        "devServerTarget": "project:serve",
                        "watch": true,
                        "headless": true,
                        "spec": "cypress/integration/project/**"
                    },
                    "configurations": {
                        "production": {
                            "devServerTarget": "project:serve:production"
                        }
                    }
                }`

**Comment by anthonymjones** [comment]
That’s great to hear, thanks for retesting!
