### ISSUE TITLE
removeProtractor no longer removes e2e directory

### ISSUE THREAD

**Issue by cexbrayat** [briebug/cypress-schematic#62]
**Describe the bug**

With v4.0.2, the `--remove-protractor` does update package.json but does not remove the e2e directory.

**To Reproduce**

Using CLI 10.1

```
ng new remove-protractor --defaults
cd remove-protractor
ng add @briebug/cypress-schematic --remove-protractor
```
 The `e2e` directory is till there.

**Expected behavior**

The directory should be removed as it was in v3.x

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by anthonymjones** [comment]
Thank you @cexbrayat, looking into the issue now

**Comment by anthonymjones** [comment]
It appears that in the latest version of the @angular-devkit/schematics code, using `tree.exists('./e2e')` does not work. Pushing up an update and will release this fix this morning. Thanks for catching this!
