### ISSUE TITLE
cypress/tsconfig.json could be added to the lint config

### ISSUE THREAD

**Issue by cexbrayat** [briebug/cypress-schematic#63]
**Is your feature request related to a problem? Please describe.**

With v4.0.3, the `--remove-protractor` flag does remove `e2e/tsconfig.json` from `angular.json` but does not add the new `cypress/tsconfig.json` to the `lint` config.

**Describe the solution you'd like**

Using CLI 10.1

```
ng new remove-protractor --defaults
cd remove-protractor
ng add @briebug/cypress-schematic --remove-protractor
```
 The `lint` config is:
```json
"lint": {
  "builder": "@angular-devkit/build-angular:tslint",
  "options": {
    "tsConfig": ["tsconfig.app.json", "tsconfig.spec.json"],
    "exclude": ["**/node_modules/**"]
  }
},
```

it could be:

```json
"lint": {
  "builder": "@angular-devkit/build-angular:tslint",
  "options": {
    "tsConfig": ["tsconfig.app.json", "tsconfig.spec.json", "cypress/tsconfig.json"],
    "exclude": ["**/node_modules/**"]
  }
},
```

**Describe alternatives you've considered**

It can be added manually of course, but if you forgot, you don't lint the cypress directory.

**Comment by muuvmuuv** [comment]
`tslint` is deprecated. I suggest you to switch over to ESLint with Angular: https://github.com/angular-eslint/angular-eslint

**Comment by cexbrayat** [comment]
@muuvmuuv Thank you for your answer, but I want to point out that this is not really related: the `lint` task of the CLI is here to stay even after we migrate to a different builder in the future. (for the record: I'm a CLI contributor and contributed to the lint part for a long time 🙂  ). 

Even when the migration to ESLint will be completed (and that will not be before some time, as the work just started), the tsconfig file for the Cypress directory will most probably need to be included in the task configuration.

**Comment by muuvmuuv** [comment]
True that, it should be included anyway ^^ just wanted to point that out if you weren't already aware of cool eslint. I am using angular-eslint in an enterprise ng app and it's running smoothly.

**Comment by muuvmuuv** [comment]
I am working on it.
