### ISSUE TITLE
baseUrl being overridden

### ISSUE THREAD

**Issue by craig-dae** [briebug/cypress-schematic#64]
**Describe the bug**
Despite setting the baseUrl in my cypress.json file, it is being overridden by this library. Cypress reports that the cli is setting the baseUrl explicitely to `http://localhost:4200/`. However, I need my baseUrl to be `http://localhost.localdomain:8080`, or my tests will fail. 

**To Reproduce**
Override the baseUrl in cypress.json, or in an environment variable, and run cypress as normal. Confirm intended behavior. Then us `ng e2e` configured in angular.json as follows: 

```
        "e2e": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "app:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "app:serve:production"
            }
          }
        },
```

and cypress, will open in http://localhost:4200/, and will make endpoint calls against that url as well, even when it was configured differently. When you go to the cypress configuration menu, you will see this value has been set in the CLI

**Expected behavior**
The CLI should not override the baseUrl set in the project

**Comment by anthonymjones** [comment]
Hi @craig-dae! This should be fixed as of v4.2.0, please re-test using `ng add @briebug/cypress-schematic@latest`. If it's still an issue, let me know and we'll re-open.

**Comment by craig-dae** [comment]
@anthonymjones that appears to get me through one bug. But now I'm getting Invalid Host Header. Configuring `ng e2e` with the same settings as ng serve does not appear to resolve the issue: 
    "start": "find . -name 'core.[[:digit:]]*' -delete 2> /dev/null;  ng build odin-shared; node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --disable-host-check",
    "coverage": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng e2e --host 0.0.0.0 --disable-host-check",

Any clue? Google isn't helping me a lot with code coverage troubleshooting.

**Comment by craig-dae** [comment]
Ok, got through it. 

--disable-host-check does not work when running e2e. However, adding it to your angular.json file does work. 

```
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build",
            "disableHostCheck": true
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
```

Because the e2e definition inherits the serve definition, it picks up the disable host check and works. 

I think we're in business now.

**Comment by anthonymjones** [comment]
Awesome! Glad you were able to get through that.
