### ISSUE TITLE
cannot pass configFile as a user config option

### ISSUE THREAD

**Issue by cogoo** [briebug/cypress-schematic#67]
**Describe the bug**
The cypress API allows you to pass a `configFile` as an [option](https://docs.cypress.io/guides/guides/module-api.html#Options). The cypress builder doesn't allow this option

**Expected behaviour**
The builder should expose the full options list provided by the cypress API

**Additional context**
I'll be more than happy to submit a PR for this :)

**Comment by anthonymjones** [comment]
Thanks @cogoo, that would be great to have you submit a PR on this!

**Comment by rkrisztian** [comment]
I am now also interested in said "full options list" for the `quiet` option.

**Comment by anthonymjones** [comment]
@konstantindenerz has a fix for this coming soon.

@rkrisztian - this is the only options list I'm aware of: https://docs.cypress.io/guides/guides/command-line.html#Commands

**Comment by rkrisztian** [comment]
@anthonymjones , that is fine, thanks.

**Comment by anthonymjones** [comment]
This should be fixed now, please re-open if the issue persists. Run `ng add @briebug/cypress-schematic@latest` to make sure you have the latest changes.
