### ISSUE TITLE
Ability to control quiet mode

### ISSUE THREAD

**Issue by rkrisztian** [briebug/cypress-schematic#73]
In #67 I mistakenly thought that the [option `quiet`](https://docs.cypress.io/guides/guides/module-api.html#Options) would also be exposed to us in `angular.json`, because that ticket says:

> The builder should expose the full options list provided by the cypress API

Sadly, adding `quiet` to the Cypress configuration file does not work, it's ignored there. It's either a command-line flag or a module option. And the Cypress devs do not want to expose that option it in any other way, as far as I understood (e.g. not as an environment variable), see: https://github.com/cypress-io/cypress/issues/8813 .

So this leaves me with asking you guys to help me with my configuration for CI builds. Thank in advance.

**Comment by anthonymjones** [comment]
Thanks @konstantindenerz, I’ll cut a release in a bit. Thank you @rkrisztian for bringing this back up
