### ISSUE TITLE
Please support Firefox

### ISSUE THREAD

**Issue by rkrisztian** [briebug/cypress-schematic#76]
The `browser` option is currently limited to the Chrome family. I would like to make it possible to run the tests also in Firefox, as I need it for the use of the `cypress/browsers` image, which seems to work after temporarily removing the `enum` from `node_modules/@briebug/cypress-schematic/src/builders/cypress/schema.json`:

To be exact, developers are likely to find it more convenient to run the Firefox browser that is installed on their system directly, so the docker container is just an other use case. But my feature request would transparently support both cases of course.

**Comment by anthonymjones** [comment]
Hi @rkrisztian - Thanks for bringing this to my attention. Support for Firefox has been added in [this release](https://github.com/briebug/cypress-schematic/releases/tag/v4.3.0). Please try adding again using `ng add @briebug/cypress-schematic@latest`. Please let me know if there are any other issues you find!
