### ISSUE TITLE
Cypress 6.0.0 Support

### ISSUE THREAD

**Issue by osiastedian** [briebug/cypress-schematic#78]
**Describe the bug**
I tried updating Cypress to `6.0.0` via `yarn upgrade cypress@6.0.0`.
Every time I do `ng run {project}:cypress-run` it always spins up cypress version `5.6.0`.

**To Reproduce**
1. run `yarn upgrade cypress@6.0.0`
2. Run cypress command `ng run {project}:cypress-run`
3. New cypress intercept is not working `TypeError: cy.intercept is not a function` 

**Expected behavior**
It's should run on Cypress 6.0.0

**Screenshots**
![Screen Shot 2020-11-25 at 10 04 21 AM](https://user-images.githubusercontent.com/11253903/100173688-f5327a00-2f05-11eb-9d60-c643c2f4a0cd.png)
![Screen Shot 2020-11-25 at 10 04 43 AM](https://user-images.githubusercontent.com/11253903/100173695-f82d6a80-2f05-11eb-90e5-432829bd01b9.png)
![Screen Shot 2020-11-25 at 10 05 08 AM](https://user-images.githubusercontent.com/11253903/100173697-f8c60100-2f05-11eb-9562-4b2173601611.png)
![Screen Shot 2020-11-25 at 10 09 01 AM](https://user-images.githubusercontent.com/11253903/100173902-64a86980-2f06-11eb-809e-f884b88836fa.png)
![Screen Shot 2020-11-25 at 10 09 19 AM](https://user-images.githubusercontent.com/11253903/100173905-66722d00-2f06-11eb-8b2e-536e3d2fc228.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser N/A
 - Version node v12.18.4

**Additional context**
I think this is just a peer dependency issue. I can PR a fix if that's okay.

**Comment by anthonymjones** [comment]
Thanks for the PR @osiastedian!
