### ISSUE TITLE
Improvement of DX with CLI builders

### ISSUE THREAD

**Issue by mgechev** [briebug/cypress-schematic#8]
Fantastic effort with this new project! I have a couple of recommendation which you can address to achieve optimal development experience with the latest capabilities of the Angular CLI:

- [x] Replace the instructions in the readme with `ng add @briebug/cypress-schematic`. Since you have `ng-add` schematic, `ng add` will install the package and execute them. No need to install it globally.
- [x] Implement a custom [builder](https://angular.io/guide/cli-builder) that runs Cypress. Instead of executing Cypress as an npm script, you can wrap it inside of a custom CLI builder. This way you'll be able to invoke it directly via the Angular CLI with `ng run [project-name]:cypress`, or even `ng e2e`
- [x] Replace the existing `e2e` builder with Cypress one when the user wants to remove Protractor. This step is quite easy. In the `ng-add` schematic you can transform `angular.json` and replace the `e2e` builder to point to your own (Cypress one) instead of Protractor.

This way, the default flow would be:

```bash
$ ng add @briebug/cypress-schematic
// Confirm removal of Protractor
$ ng e2e
```

Let me know if I can help somehow!

**Comment by anthonymjones** [comment]
Addressed and completed these enhancements in PR #16. Thanks for the suggestions @mgechev!
