### ISSUE TITLE
Denpendency question

### ISSUE THREAD

**Issue by just-trey** [briebug/cypress-schematic#81]
**Is your feature request related to a problem? Please describe.**
This is a question. Why does the schematic `@briebug/cypress-schematic` get added in `dependencies` rather than in `devDependencies` in the `package.json`. It seems odd to me that this schematic would be used for anything in the built application. 

**Describe the solution you'd like**
If it is not leveraged in part ofd the built application the schematic should add in `devDependencies` if it is needed. 

**Describe alternatives you've considered**
Manually moving the dependency to `devDependencies` the after it is installed. 

**Additional context**
N/A

**Comment by schuchard** [comment]
this should fix it: https://github.com/schuchard/prettier-schematic/blob/master/package.json#L32-L34

**Comment by anthonymjones** [comment]
@schuchard - That appears to already be in this repository: https://github.com/briebug/cypress-schematic/blob/bd8609238ded4b36c00f984b2953592d06f5a398/package.json#L47-L49. I'm not sure what might be causing this.

**Comment by schuchard** [comment]
I tested locally with angular 11 and this schematic was added to the devDependencies. Older angular versions did not allow for control of dependencies vs devDependencies.

@just-trey what version of angular & angular/cli are you using?

**Comment by anthonymjones** [comment]
I'm going to close this issue, let us know if you need anything else @just-trey!

**Comment by just-trey** [comment]
@anthonymjones thank you. I am on an earlier version of Angular so this makes sense
