### ISSUE TITLE
Invalid JSON character for "ng add @briebug/cypress-schematic"

### ISSUE THREAD

**Issue by MMLino** [briebug/cypress-schematic#84]
**Describe the bug**
After I tried to add the schematics as a dependency for my Angular 9 project I faced with the "Invalid JSON character" error

**How to reproduce:**
1. install cypress --> _npm i @briebug/cypress-schematic_
2. add schematics --> _ng add @briebug/cypress-schematic_
3. say "Yes" for the question "? Would you like to remove Protractor from the project?"
4. ERROR --> **Invalid JSON character: "\n" at 83:21.**

**Code:**
`ng add @briebug/cypress-schematic`
`Skipping installation: Package already installed`
`? Would you like to remove Protractor from the project? Yes`
`Invalid JSON character: "\n" at 83:21.`

**Expected behavior**
schematics added.

**Desktop (please complete the following information):**
 - OS: Windows 10 19041.63
 - IDE: Visual Studio Code

**Comment by anthonymjones** [comment]
Hi @MMLino, thanks for reaching out with this issue! Let's see if we can get this working for you.

First, you shouldn't need to install @briebug/cypress-schematic as a dependency. Running `ng add @briebug/cypress-schematic` should be enough, but I often run it as `ng add @briebug/cypress-schematic@latest` just to make sure I'm on the most recent version. Right now, that should be v4.4.0. 

However, based on the error you're seeing (**Invalid JSON character: "\n" at 83:21.**), it sounds like there might be something going on in your angular.json file. Are you able to post the contents of your angular.json file? Or at least the 20-50 lines around line 83?

Just to gather a little more info, is this a single or monorepo? Also, is there a reason you haven't yet updated to Angular 10 or 11?

**Comment by MMLino** [comment]
Hi @anthonymjones, sorry for the delay in my response.

Upgrading angular to v11 and running `ng add @briebug/cypress-schematic@latest` I noticed that all is working now.

Many thanks,
BR
Marco

**Comment by anthonymjones** [comment]
Glad to hear it! Thanks for the update Marco :)
