### ISSUE TITLE
Script stops without doing anything (and no error)

### ISSUE THREAD

**Issue by paulholleis** [briebug/cypress-schematic#86]
**Describe the bug**
Running `ng add @briebug/cypress-schematic` on a new Angular project just doesn't do anything for me, no output or changes (except adding the "@briebug/cypress-schematic": "^4.4.0" dev-dependency to package.json). Doesn't exit within an hour or so. Parameters `--addCypressTestScripts` or `--noBuilder` do not make any difference. Same with "yes" or "no" to whether Protractor should be removed or not. `ng build`runs without issues.

```
npx @angular/cli new cypresstest
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
CREATE cypresstest/README.md (1020 bytes)
CREATE cypresstest/.editorconfig (274 bytes)
CREATE cypresstest/.gitignore (631 bytes)
CREATE cypresstest/angular.json (3745 bytes)
CREATE cypresstest/package.json (1201 bytes)
CREATE cypresstest/tsconfig.json (737 bytes)
CREATE cypresstest/tslint.json (3185 bytes)
CREATE cypresstest/.browserslistrc (703 bytes)
CREATE cypresstest/karma.conf.js (1428 bytes)
CREATE cypresstest/tsconfig.app.json (287 bytes)
CREATE cypresstest/tsconfig.spec.json (333 bytes)
CREATE cypresstest/src/favicon.ico (948 bytes)
CREATE cypresstest/src/index.html (297 bytes)
CREATE cypresstest/src/main.ts (372 bytes)
CREATE cypresstest/src/polyfills.ts (2826 bytes)
CREATE cypresstest/src/styles.scss (80 bytes)
CREATE cypresstest/src/test.ts (753 bytes)
CREATE cypresstest/src/assets/.gitkeep (0 bytes)
CREATE cypresstest/src/environments/environment.prod.ts (51 bytes)
CREATE cypresstest/src/environments/environment.ts (662 bytes)
CREATE cypresstest/src/app/app-routing.module.ts (245 bytes)
CREATE cypresstest/src/app/app.module.ts (393 bytes)
CREATE cypresstest/src/app/app.component.scss (0 bytes)
CREATE cypresstest/src/app/app.component.html (25757 bytes)
CREATE cypresstest/src/app/app.component.spec.ts (1072 bytes)
CREATE cypresstest/src/app/app.component.ts (216 bytes)
CREATE cypresstest/e2e/protractor.conf.js (904 bytes)
CREATE cypresstest/e2e/tsconfig.json (274 bytes)
CREATE cypresstest/e2e/src/app.e2e-spec.ts (662 bytes)
CREATE cypresstest/e2e/src/app.po.ts (274 bytes)
✔ Packages installed successfully.
    Successfully initialized git.

cd cypresstest

ng add @briebug/cypress-schematic
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Would you like to remove Protractor from the project? Yes
```

**Additional context**
OS: Mac OS Big Sur

Angular CLI: 11.0.4
Node: 14.15.1
OS: darwin x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5

**Comment by anthonymjones** [comment]
@paulholleis - Thanks for reaching out with this issue. Unfortunately, I'm unable to reproduce this behavior at the moment. I have all the same versions as you (CLI, Node, Angular, etc.), the only difference is that I haven't upgraded to Big Sur on my Mac. I'll see if anyone I know who has done the upgrade can test this out and reproduce.

**Comment by paulholleis** [comment]
@anthonymjones no worries - if I can do anything to shed light on what happens (or not), please let me know!

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
