### ISSUE TITLE
Invalid JSON character: "\t" at...

### ISSUE THREAD

**Issue by chrisleyva** [briebug/cypress-schematic#87]
When trying add the cypress-schematic, I run into an `Invalid JSON character` issue, similar to the issue experienced with the [jest-schematic](https://github.com/briebug/jest-schematic/issues/4)

```zsh
> ng add @briebug/cypress-schematic@latest
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Would you like to remove Protractor from the project? Yes
Invalid JSON character: "\t" at 79:17.
```

Angular Versions
------
Angular CLI: 10.2.1
Node: 12.16.1
OS: darwin x64  **macOS Catalina 10.15.7** 

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package          |                 Version
---------------|-------------------------------------------
@angular-devkit/architect         |0.1001.7
@angular-devkit/build-angular     |0.1001.7
@angular-devkit/build-optimizer   |0.1001.7
@angular-devkit/build-webpack     |0.1001.7
@angular-devkit/core              |10.2.1
@angular-devkit/schematics        |10.2.1
@angular/cdk                      |10.2.7
@angular/cli                      |10.2.1
@angular/flex-layout              |10.0.0-beta.32
@angular/material                 |10.2.7
@ngtools/webpack                  |10.2.1
@schematics/angular               |10.2.1
@schematics/update                |0.1001.7
rxjs                              |6.6.3
typescript                        |3.9.7
webpack                           |4.46.0

**Comment by chrisleyva** [comment]
Welp, here's what fixed it for me:

Convert all the tabs to spaces in my `packages.json` file. 🤦‍♂️

**Comment by anthonymjones** [comment]
Thank you @chrisleyva! I'll look into this.

**Comment by chrisleyva** [comment]
@anthonymjones No problem.
I tried forking the project to see if I could run it locally and see what was going on but I couldn't run it.

The `npm link` command would remove needed packages from the sandbox. And then I couldn't run it without linking. So it was a weird chicken & egg issue. In the end, I had to just give up. And I don't remember the specific errors right now.

I'd be willing to give it another shot when I have some more time in 2 weeks.

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
