### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by TonySpegel** [briebug/cypress-schematic#88]
**Describe the bug**
While setting up a project and adding this schematic I get a dependency error I can't make sense of. 
Files are getting created but it fails nonethless.

**To Reproduce**
1. Start a new project using the angular cli (e. .g.: `ng new e-paper-dashboard`) , I've chosen adding the router, scss and strict mode
2. Add the schematic `npx ng add @briebug/cypress-schematic`
3. See error

**Expected behavior**
Adding the schematic w/o getting any errors

**Terminal output**
```bash
npx ng add @briebug/cypress-schematic                                                            ✔  10:23:15

ℹ Using package manager: npm
✔ Found compatible package version: @briebug/cypress-schematic@4.4.0.
✔ Package information loaded.
✔ Package successfully installed.
? Would you like to remove Protractor from the project? Yes
DELETE e2e
CREATE cypress.json (299 bytes)
CREATE cypress/tsconfig.json (140 bytes)
CREATE cypress/integration/spec.ts (103 bytes)
CREATE cypress/plugins/cy-ts-preprocessor.js (425 bytes)
CREATE cypress/plugins/index.js (158 bytes)
CREATE cypress/support/commands.ts (1377 bytes)
CREATE cypress/support/index.ts (651 bytes)
UPDATE package.json (1320 bytes)
UPDATE angular.json (4533 bytes)
⠹ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: e-paper-dashboard@0.0.0
npm ERR! Found: webpack@5.24.2
npm ERR! node_modules/webpack
npm ERR!   peer webpack@">=2" from babel-loader@8.2.2
npm ERR!   node_modules/babel-loader
npm ERR!     peer babel-loader@"^8.0.2" from @cypress/webpack-preprocessor@5.6.0
npm ERR!     node_modules/@cypress/webpack-preprocessor
npm ERR!       dev @cypress/webpack-preprocessor@"5.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.18.1" from @cypress/webpack-preprocessor@5.6.0
npm ERR! node_modules/@cypress/webpack-preprocessor
npm ERR!   dev @cypress/webpack-preprocessor@"5.6.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/tony/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2021-03-02T09_24_16_058Z-debug.log
````

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome 88.0.4324.192
 - Schematic version: 4.4.0
 - NPM version: 7.6.0
 - Node version: 15.10.0

I hope this helps a bit as I can't make much sense frome the error message above.

Thank you :)

**Comment by muuvmuuv** [comment]
Seems it is mixing two Webpacks versions here. Can you try using Webpack 4 instead and try it again?

```
npm ERR! peer webpack@"^4.18.1" from @cypress/webpack-preprocessor@5.6.0
```

I guess **@cypress/webpack-preprocessor** needs to be updated here to work with Webpack 5.

**Comment by TonySpegel** [comment]
I honestly don't know how to set a different Webpack version for an Angular project, it's configured as it comes when starting a new project with the CLI

**Comment by muuvmuuv** [comment]
Try using yarn instead of npm. Just remove your node_modules and package-lock.json and do `npm i -g yarn`. Then add `{ resolutions: { "webpack": "4" } }` into your package.json and run yarn in the root. It should no pin all webpack dependences to v4. Or try with webpack 5 as a resolution.

**Comment by TonySpegel** [comment]
Thx for the solution but shouldn't it work with the most common package managers not just yarn? Not a huge fan of installing yarn just for that^^,
I'm not demanding anything btw I thank you for your solution but I guess I'll add Cypress manually then.

**Comment by muuvmuuv** [comment]
npm does not currently support resolutions, so it's needed until cypress-schematic is updated to work with Webpack 5. I can recommend you pnpm if you don't want to use yarn.

**Comment by muuvmuuv** [comment]
Anyway, can you confirm that it is working with the resolution fix? If not its something else, but I bet it's that version miss match, had that a lot the last month when packages update to use Webpack 5

**Comment by paolobittante** [comment]
@TonySpegel I think the issue is related to npm version, since from V7 it automatically tries to resolve peer dependencies.

With V6, I didn't have problems. A workaround for V7 would be to execute `npm i --legacy-peer-deps`and in this way the command ignore peer dependencies entirely (this behaviour is similar to versions 4-6).

@muuvmuuv I tried your proposal, but it didn't work.

**Comment by anthonymjones** [comment]
As of 7/27/21, this schematic is no longer supported. The Cypress Angular Schematic has been adopted by Cypress and will be maintained in their repository by the Cypress Team moving forward. Head over to https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic for more info.
