### ISSUE TITLE
baseUrl from angular.json not applied

### ISSUE THREAD

**Issue by bfoese** [briebug/cypress-schematic#89]
**Describe the bug**
I tried to define the 'baseUrl' in angular.json instead of cypress.json, but it wasn't applied in Cypress. Debugging into it, I found out that it was not applied, because Cypress expects an options object with baseUrl like this:
`type cyOptions = { config: { baseUrl: string }};`
but cypress-schematic provided 
`type cySchematicOptions = { baseUrl: string };`

**To Reproduce**
1. Define baseUrl in angular.json (make sure NOT to define 'devServerTarget' as this would overrule 'baseUrl')

`    "e2e": {  
    "builder": "@briebug/cypress-schematic:cypress",  
    "options": {  
        "watch": true,  
        "headless": false,  
        "configFile": "projects/seed-sharing-app/cypress.json",  
        "baseUrl": "https://my-base-url.com"  
    }  
    }`
 
2. Run e2e tests: `ng e2e --app my-app`

3. Check applied settings in Cypress window
![image](https://user-images.githubusercontent.com/1623552/111842835-60161f80-8900-11eb-88ec-e79090b8ae3c.png)
Provided 'baseUrl' is null but I would expect it to be "https://my-base-url.com" instead.
If you run the same test with a baseUrl provided in cypress.json, then the cypress window would show the baseUrl from cypress.json.

**Expected behavior**
'baseUrl' value from angular.json must be applied in Cypress tests and should also overrule the 'baseUrl' from cypress.json, in case both are provided. 

**Screenshots**
The first screenshot is from Cypress open.js which is called by cypress-schematic via `initCypress()`:
![image](https://user-images.githubusercontent.com/1623552/111844882-22b39100-8904-11eb-85dd-abdff9b2de3b.png)
You can see that the options for browser, env, port ect. are directly taken from 'options', whereas 'baseUrl' is not.
Cypress expects 'baseUrl' to be part of the options.config object:
![image](https://user-images.githubusercontent.com/1623552/111845147-9786cb00-8904-11eb-8fbd-9082921cde37.png)
https://docs.cypress.io/guides/references/configuration.html#Options

The problem is the part in initCypress where the 'options' object is being built for Cypress. 
![image](https://user-images.githubusercontent.com/1623552/111845396-06fcba80-8905-11eb-9b6a-c6f19ebaf44e.png)

A possible fix could look like this, in case my assumption that baseUrl from angular.json must overrule baseUrl from cypress.json is correct:
![image](https://user-images.githubusercontent.com/1623552/111848201-ce5fdf80-890a-11eb-88a1-5ee57802cc76.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Cypress Version: 6.6.0 & 6.8.0

**Comment by muuvmuuv** [comment]
This is weird because as you can see the userOptions is just passed into options without any further overrides so it should be in there. I will check what is going on here.

**Comment by muuvmuuv** [comment]
Oh, now I got it, it is not included in the config part of options. It's monday... :D PR incoming
