### ISSUE TITLE
Custom commands not recognized

### ISSUE THREAD

**Issue by BojanKogoj** [briebug/cypress-schematic#90]
**Describe the bug**
When creating custom command it is not recognized.

**To Reproduce**
Add to commands.ts
```ts
Cypress.Commands.add('dataCy', (value) => cy.get(`[data-cy=${value}]`));
```

**Output**
```
TS2339: Property 'dataCy' does not exist on type 'cy & EventEmitter'.
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 89

**Additional context**
This is fresh install of Cypress. The command above worked on another project, made without cypress-schematic.

**Comment by bfoese** [comment]
I'd say this is not an issue of this plugin. Did you declared the command also in the Cypress namespace? Here is an example:

```javascript
// content of commands.ts
declare namespace Cypress {
  interface Chainable<Subject = any> {
    verifySuccessfulSigninAndSignout(): typeof verifySuccessfulSigninAndSignout;
  }
}

function verifySuccessfulSigninAndSignout(): void {
// command implementation
}

Cypress.Commands.add("verifySuccessfulSigninAndSignout", verifySuccessfulSigninAndSignout);
```
Or if you have this namespace declaration in a different file, then make sure it is imported into cypress/support/index.ts which also imports the commands file.

**Comment by BojanKogoj** [comment]
You were right, it works this way.
I haven't managed to make it work before because when saving commands.ts you need to restart cypress, since it doesn't rebuild with changes for some reason.
