### ISSUE TITLE
Cypress 7 support

### ISSUE THREAD

**Issue by spicemix** [briebug/cypress-schematic#91]
Cypress 7 isn't supported yet, but I manually updated the dependencies to 7 much like https://github.com/briebug/cypress-schematic/pull/79 did and things worked for me in 7. So it may be as simple to add...thanks!

**Comment by cexbrayat** [comment]
@anthonymjones as this issue arises every time Cypress releases a major version, maybe the dependency could be a peer dependency only? That would let developers set the version they want in their projects, no?
