### ISSUE TITLE
Cannot read property 'tap' of undefined : ts-loader v9 is incompatible and breaks the schematics

### ISSUE THREAD

**Issue by cexbrayat** [briebug/cypress-schematic#97]
**Describe the bug**

ts-loader v9 has been released yesterday (https://github.com/TypeStrong/ts-loader/releases/tag/v9.0.0), and is incompatible with webpack 4.
This means that the current schematics stopped working when trying to install in an Angular CLI project (v12 will use Webpack 5, but it's not the case for Angular CLI 11).

```
Oops...we found an error preparing this test file:

  cypress/integration/spec.ts

The error was:

Error: Webpack Compilation Error
./cypress/integration/spec.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'tap' of undefined

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

Oops...we found an error preparing this test file:

  cypress/support/index.ts

The error was:

Error: Webpack Compilation Error
./cypress/support/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'tap' of undefined

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**To Reproduce**

PR #68 adds the sandbox test to the CI build, and now fails since yesterday (see https://github.com/briebug/cypress-schematic/runs/2378789191?check_suite_focus=true)

**Expected behavior**

The schematics should work out of the box

**Additional context**

It is possible to fix the issue by using the previous version of ts-loader as a workaround.

But the proper fix would probably be to remove the TS preprocessor that uses ts-loader, as it is no longer necessary.
There is already a PR ready to do so : see #94

**Comment by dnepro** [comment]
Awesome, i've been searching for the issue for the last 2 to 3 hours, awesome to see it already fixed!

**Comment by cexbrayat** [comment]
@dnepro You're welcome 😉

@anthonymjones Do you think you'll be able to cut a release including the fix soon?
